// Edit this file to update site content.

const SITE = {

  // ── BRAND ─────────────────────────────────────
  name: 'Vertex Infras',
  fullName: 'Vertex Infras',
  tagline: 'Towards Finest Engineering',
  email: 'hello@vertexinfras.com',
  projectsEmail: 'projects@vertexinfras.com',
  phone: ['+91 22 4567 8900', '+91 98765 43210'],
  address: '123 Infrastructure Lane, Bandra West<br>Mumbai, Maharashtra 400050',
  social: {
    linkedin: '#',
    twitter: '#',
    instagram: '#',
  },

  // ── NAVIGATION ────────────────────────────────
  nav: [
    { text: 'Home',         href: 'index.html' },
    { text: 'About',        href: 'about.html' },
    { text: 'Projects',     href: 'projects.html' },
    { text: 'Testimonials', href: 'testimonials.html' },
    { text: 'Contact',      href: 'contact.html' },
  ],

  // ── PAGE BANNERS (inner pages) ────────────────
  banners: {
    about:        { title: 'About Us',      sub: 'Precision engineering, lasting impact' },
    projects:     { title: 'Our Projects',   sub: 'A portfolio of landmark infrastructure' },
    testimonials: { title: 'Testimonials',   sub: 'Trusted by industry leaders across India' },
    contact:      { title: 'Contact Us',     sub: 'Find your dream home, apartment, or villa — we\'re here to help' },
  },

  // ── HERO (home only) ─────────────────────────
  hero: {
    heading: 'The Home You Deserve,<br>The Life You <em>Earned</em>',
    sub: 'Every detail thoughtfully designed, every space carefully crafted — because where you live should feel as good as the life you\'ve worked hard to build.',
    ctaPrimary: { text: 'Explore Projects', href: 'projects.html' },
    ctaSecondary: { text: 'Our Story', href: 'about.html' },
  },

  // ── STATS ─────────────────────────────────────
  stats: [
    { value: 55, label: 'Projects Delivered' },
    { value: 27, label: 'Years of Excellence' },
  ],

  // Full-bleed sections on the home page. Uncomment `image` when you have real photos.
  featured: [
    {
      title: 'Vertex Vista',
      subtitle: '4 BHK luxury villas in Varthur',
      tag: 'Ready to Move In',
      badge: 'Ready to Move In',
      desc: 'Spacious 4 BHK independent villas in a premium gated community in Varthur, Bengaluru — ready for immediate possession.',
      stat1: { value: '21', label: 'Villas' },
      stat2: { value: '4 BHK', label: 'Configuration' },
      stat3: { value: 'Varthur', label: 'Location' },
      bg: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 40%, #1e1e1e 100%)',
      // image: 'images/vista-hero.jpg',
      cta: { text: 'View Project', href: 'projects.html' },
    },
    {
      title: 'Vertex Wellington',
      subtitle: 'Premium apartments in Gunjur',
      tag: 'Booking Open',
      badge: 'Selling Fast',
      desc: 'Well-planned 2 & 3 BHK apartments in the rapidly growing Gunjur corridor, with excellent connectivity to Sarjapur Road.',
      stat1: { value: '2 & 3', label: 'BHK' },
      stat2: { value: 'Gunjur', label: 'Location' },
      stat3: { value: '2025', label: 'Possession' },
      bg: 'linear-gradient(135deg, #1e1e1e 0%, #2a2a20 40%, #1e1e1e 100%)',
      // image: 'images/wellington-hero.jpg',
      cta: { text: 'View Project', href: 'projects.html' },
    },
    {
      title: 'Vertex Vihanta',
      subtitle: 'Coming soon to Bengaluru',
      tag: 'Pre-Launch',
      badge: 'Pre-Launch',
      desc: 'Our upcoming landmark residential project — register your interest now to get early access to pricing and floor plans.',
      stat1: { value: 'TBA', label: 'Configuration' },
      stat2: { value: 'Bengaluru', label: 'Location' },
      stat3: { value: '2026', label: 'Possession' },
      bg: 'linear-gradient(135deg, #1a1a1a 0%, #2a2528 40%, #1e1e1e 100%)',
      // image: 'images/vihanta-hero.jpg',
      cta: { text: 'Register Interest', href: 'contact.html' },
    },
  ],

  // ── ABOUT ─────────────────────────────────────
  about: {
    tag: 'Who We Are',
    heading: 'Precision Engineering,<br>Lasting Impact',
    paragraphs: [
      'Vertex Infras is a premier civil engineering consultancy committed to shaping India\'s infrastructure landscape. We bring together deep technical expertise, innovative design thinking, and an unwavering commitment to quality.',
      'From concept to completion, our multidisciplinary team delivers solutions across structural, geotechnical, transportation, and environmental engineering — projects that communities depend on for generations.',
    ],
    badgeNum: '27+',
    badgeLabel: 'Years',
    values: [
      { icon: 'check',  title: 'Quality Assurance', desc: 'ISO-certified processes at every stage' },
      { icon: 'layers', title: 'BIM Integrated',    desc: 'Advanced 3D modeling & planning' },
      { icon: 'team',   title: 'Expert Team',       desc: '50+ licensed professional engineers' },
      { icon: 'shield', title: 'Safety First',      desc: 'Zero-incident commitment on every site' },
    ],
    // Add photo paths when ready
    team: [
      {
        name: 'Pradeep Reddy',
        role: 'Founding Director',
        // photo: 'images/team/pradeep.jpg',
        bio: 'Civil engineer with 27+ years of experience delivering residential and infrastructure projects across South India.',
      },
      {
        name: 'Srinivas Reddy',
        role: 'Founding Director',
        // photo: 'images/team/srinivas.jpg',
        bio: 'Civil engineer specialising in large-scale construction, project planning, and quality execution.',
      },
      {
        name: 'Venkatesh Reddy',
        role: 'Founding Director',
        // photo: 'images/team/venkatesh.jpg',
        bio: 'Structural designer with deep expertise in residential and commercial structural systems.',
      },
    ],
    pastProjects: [
      {
        title: 'Vertex Venezia', location: 'East Bengaluru',
        type: '2 BHK Apartments', status: 'Sold Out', year: 2020,
        // image: 'images/past/venezia.jpg',
      },
      {
        title: 'Vertex Fairmount', location: 'South Bengaluru',
        type: '2 & 3 BHK Apartments', status: 'Sold Out', year: 2019,
        // image: 'images/past/fairmount.jpg',
      },
      {
        title: 'Vertex Wellington', location: 'Gunjur, Bengaluru',
        type: '2 & 3 BHK Apartments', status: 'Sold Out', year: 2022,
        // image: 'images/past/wellington.jpg',
      },
    ],
  },

  // `bg`: card gradient class (proj-1 … proj-6). `image`: optional real photo path.
  projects: {
    tag: 'Portfolio',
    heading: 'Featured Projects',
    desc: 'A selection of landmark projects that reflect our engineering precision and commitment to excellence.',
    items: [
      {
        id: 'vertex-vista',
        tag: 'Villas', category: 'villas', title: 'Vertex Vista', bg: 'proj-1',
        desc: 'Spacious 4 BHK independent villas in a premium gated community in Varthur, ready for immediate possession.',
        location: 'Varthur, Bengaluru', year: 2024, stat: '21 Villas',
        status: 'Ready to Move In',
        fullDesc: 'Vertex Vista is an exclusive gated community of 21 independent 4 BHK villas in Varthur, Bengaluru. Each villa is designed for families who want space, privacy, and quality — with well-proportioned layouts, private gardens, and premium finishes throughout. Ready for immediate possession.',
        specs: { units: '21 Villas', sizes: '2,034 sq ft', floors: 'G + 1 Independent Villas', possession: 'Ready to Move' },
        highlights: ['Independent 4 BHK villas', 'Private garden with each villa', 'Premium finishes throughout', 'Gated community with 24/7 security', 'Close to Varthur Main Road', 'RERA approved'],
        amenities: ['Clubhouse', 'Swimming Pool', 'Children\'s Play Area', 'Landscaped Gardens', '24/7 Security'],
        floorPlans: [{ label: '4 BHK Villa', size: '2,034 sq ft' }],
        brochure: '#',
      },
      {
        id: 'vertex-wellington-current',
        tag: 'Apartments', category: 'apartments', title: 'Vertex Wellington', bg: 'proj-2',
        desc: 'Well-planned 2 & 3 BHK apartments in the rapidly growing Gunjur corridor, selling fast.',
        location: 'Gunjur, Bengaluru', year: 2025, stat: 'Selling Fast',
        status: 'Selling Fast',
        fullDesc: 'Vertex Wellington is a thoughtfully designed residential community in the fast-growing Gunjur corridor, offering 2 and 3 BHK apartments with excellent connectivity to Sarjapur Road and the Outer Ring Road. With a full suite of amenities and quality construction, Wellington is one of the most sought-after addresses in the micro-market.',
        specs: { units: 'TBA', sizes: 'TBA', floors: 'TBA', possession: '2025' },
        highlights: ['2 & 3 BHK configurations', 'Close to Sarjapur Road & ORR', 'Full amenities package', 'Gated community', 'RERA approved'],
        amenities: ['Swimming Pool', 'Gymnasium', 'Clubhouse', 'Children\'s Play Area', 'Party Hall'],
        floorPlans: [{ label: '2 BHK', size: 'TBA' }, { label: '3 BHK', size: 'TBA' }],
        brochure: '#',
      },
      {
        id: 'vertex-vihanta',
        tag: 'Apartments', category: 'apartments', title: 'Vertex Vihanta', bg: 'proj-3',
        desc: 'Our upcoming landmark residential project in Bengaluru — register your interest for early access.',
        location: 'Bengaluru', year: 2026, stat: 'Pre-Launch',
        status: 'Pre-Launch',
        fullDesc: 'Vertex Vihanta is our next landmark residential development, coming soon to Bengaluru. Details are being finalised — register your interest now to receive early access to floor plans, pricing, and launch offers.',
        specs: { units: 'TBA', sizes: 'TBA', floors: 'TBA', possession: '2026' },
        highlights: ['Pre-launch pricing available', 'Prime Bengaluru location', 'Register now for early access'],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
      {
        id: 'vertex-placeholder-apartments',
        tag: 'Apartments', category: 'apartments', title: 'Vertex [Placeholder]', bg: 'proj-4',
        desc: 'Details coming soon. Contact us to learn more about this upcoming project.',
        location: 'Bengaluru', year: 2026, stat: 'Coming Soon',
        status: 'Coming Soon',
        fullDesc: 'This project is currently being finalised. Please get in touch with our team for more information.',
        specs: { units: 'TBA', sizes: 'TBA', floors: 'TBA', possession: 'TBA' },
        highlights: [],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
      {
        id: 'vertex-placeholder-villas',
        tag: 'Villas', category: 'villas', title: 'Vertex [Placeholder]', bg: 'proj-5',
        desc: 'Details coming soon. Contact us to learn more about this upcoming project.',
        location: 'Bengaluru', year: 2026, stat: 'Coming Soon',
        status: 'Coming Soon',
        fullDesc: 'This project is currently being finalised. Please get in touch with our team for more information.',
        specs: { units: 'TBA', sizes: 'TBA', floors: 'TBA', possession: 'TBA' },
        highlights: [],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
    ],
    pastProjects: [
      {
        id: 'vertex-venezia',
        title: 'Vertex Venezia', location: 'East Bengaluru',
        type: '2 BHK Apartments', category: 'apartments', status: 'Sold Out', year: 2020,
        tag: 'Apartments', bg: 'proj-1',
        fullDesc: 'Vertex Venezia was a boutique residential community of 120 well-designed 2 BHK apartments in East Bengaluru. Inspired by Italian architecture, it featured colonnaded walkways, a grand fountain courtyard, and warm, welcoming interiors. Fully sold out within 6 months of launch.',
        specs: { units: '120 Units', sizes: '980 – 1,150 sq ft', floors: 'G + 12 Floors', possession: 'Delivered 2020' },
        highlights: ['Italian-inspired architecture', 'Grand fountain courtyard', 'Modular kitchen fittings', 'Covered car parking', '24/7 security', 'Close to Whitefield IT hub'],
        amenities: ['Swimming Pool', 'Gymnasium', 'Clubhouse', 'Children\'s Play Area', 'Landscaped Gardens'],
        floorPlans: [{ label: '2 BHK', size: '980 – 1,150 sq ft' }],
        brochure: '#',
      },
      {
        id: 'vertex-fairmount',
        title: 'Vertex Fairmount', location: 'South Bengaluru',
        type: '2 & 3 BHK Apartments', category: 'apartments', status: 'Sold Out', year: 2019,
        tag: 'Apartments', bg: 'proj-2',
        fullDesc: 'Vertex Fairmount set the standard for affordable luxury in South Bengaluru. With 2 and 3 BHK units spread across twin towers, the project offered spacious layouts, premium finishes, and a full suite of amenities at a competitive price point. Sold out well before possession.',
        specs: { units: '210 Units', sizes: '1,100 – 1,600 sq ft', floors: 'G + 20 Floors (2 Towers)', possession: 'Delivered 2019' },
        highlights: ['Twin-tower design', 'Spacious open-plan layouts', 'Premium sanitary fittings', 'Vastu-compliant', 'Near NICE Ring Road', 'Fully sold before possession'],
        amenities: ['Rooftop Pool', 'Gymnasium', 'Multipurpose Hall', 'Jogging Track', 'Children\'s Play Area'],
        floorPlans: [{ label: '2 BHK', size: '1,100 – 1,280 sq ft' }, { label: '3 BHK', size: '1,420 – 1,600 sq ft' }],
        brochure: '#',
      },
      {
        id: 'vertex-oakwood-villas',
        title: 'Vertex Oakwood Villas', location: 'Whitefield, Bengaluru',
        type: '4 BHK Villas', category: 'villas', status: 'Sold Out', year: 2021,
        tag: 'Villas', bg: 'proj-3',
        fullDesc: 'Vertex Oakwood Villas was an exclusive enclave of 36 independent villas nestled in the greenery of Whitefield. Each villa came with a private garden, semi-basement, and double-height living areas.',
        specs: { units: '36 Villas', sizes: '3,800 – 4,600 sq ft', floors: 'G + 1 Independent Villas', possession: 'Delivered 2021' },
        highlights: ['Private garden with each villa', 'Double-height living areas', 'Semi-basement storage', 'Gated community', 'Close to ITPL & Whitefield station'],
        amenities: ['Clubhouse', 'Swimming Pool', 'Tennis Court', 'Concierge', 'Landscaped Trails'],
        floorPlans: [{ label: '4 BHK Villa', size: '3,800 – 4,600 sq ft' }],
        brochure: '#',
      },
      {
        id: 'vertex-wellington-past',
        title: 'Vertex Wellington', location: 'Gunjur, Bengaluru',
        type: '2 & 3 BHK Apartments', category: 'apartments', status: 'Sold Out', year: 2022,
        tag: 'Apartments', bg: 'proj-4',
        fullDesc: 'Vertex Wellington brought thoughtfully planned 2 and 3 BHK apartments to the rapidly developing Gunjur corridor. Wellington became one of the fastest-selling projects in the micro-market.',
        specs: { units: '180 Units', sizes: '1,020 – 1,480 sq ft', floors: 'G + 15 Floors', possession: 'Delivered 2022' },
        highlights: ['Close to Sarjapur & ORR', 'Energy-efficient design', 'Branded fixtures & fittings', 'High rental yield area'],
        amenities: ['Swimming Pool', 'Gymnasium', 'Clubhouse', 'Children\'s Play Area', 'Party Hall'],
        floorPlans: [{ label: '2 BHK', size: '1,020 – 1,180 sq ft' }, { label: '3 BHK', size: '1,300 – 1,480 sq ft' }],
        brochure: '#',
      },
      {
        id: 'vertex-exotica',
        title: 'Vertex Exotica', location: 'Bengaluru',
        type: 'Apartments', category: 'apartments', status: 'Sold Out', year: 2018,
        tag: 'Apartments', bg: 'proj-5',
        fullDesc: 'Vertex Exotica was a premium residential development in Bengaluru, offering well-designed apartments that were sold out ahead of possession.',
        specs: { units: 'TBA', sizes: 'TBA', floors: 'TBA', possession: 'Delivered 2018' },
        highlights: ['Sold out ahead of possession', 'Premium residential community', 'Bengaluru location'],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
      {
        id: 'infosys-campus-bengaluru',
        title: 'Infosys Campus Development', location: 'Bengaluru',
        type: 'Contract — Civil & Structural', category: 'other', status: 'Completed', year: 2018,
        tag: 'Contract', bg: 'proj-6',
        fullDesc: 'Vertex Infras executed civil and structural works for the Infosys campus development in Bengaluru. The scope covered site development, internal road network, drainage systems, and structural works for support buildings — delivered on time to meet Infosys\'s operational timelines.',
        specs: { units: 'N/A', sizes: 'Campus Infrastructure', floors: 'N/A', possession: 'Completed 2018' },
        highlights: ['Campus road network & paving', 'Drainage & utility infrastructure', 'Structural works for support buildings', 'Delivered on schedule'],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
      {
        id: 'gmr-group-hyderabad',
        title: 'GMR Group Infrastructure Works', location: 'Hyderabad',
        type: 'Contract — Infrastructure', category: 'other', status: 'Completed', year: 2020,
        tag: 'Contract', bg: 'proj-1',
        fullDesc: 'Vertex Infras partnered with GMR Group to execute infrastructure and civil works at their Hyderabad developments. The project included site preparation, civil structures, utility installation, and road infrastructure.',
        specs: { units: 'N/A', sizes: 'Infrastructure Works', floors: 'N/A', possession: 'Completed 2020' },
        highlights: ['Site preparation & earthworks', 'Civil structures & foundations', 'Utility & drainage installation', 'Road and access infrastructure'],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
      {
        id: 'kempegowda-airport-bengaluru',
        title: 'Kempegowda International Airport', location: 'Bengaluru',
        type: 'Contract — Civil & Infrastructure', category: 'other', status: 'Completed', year: 2022,
        tag: 'Contract', bg: 'proj-2',
        fullDesc: 'Vertex Infras carried out civil and infrastructure works at Kempegowda International Airport, Bengaluru. The scope included structural works, pavement, drainage systems, and utility infrastructure in support of the airport\'s expansion.',
        specs: { units: 'N/A', sizes: 'Airport Infrastructure', floors: 'N/A', possession: 'Completed 2022' },
        highlights: ['Structural & pavement works', 'Drainage & stormwater systems', 'Utility infrastructure', 'Executed to aviation safety standards'],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
    ],
  },

  // ── TESTIMONIALS ──────────────────────────────
  testimonials: {
    tag: 'Client Voices',
    heading: 'Trusted by Industry Leaders',
    desc: 'Our reputation is built on consistently exceeding expectations through transparent communication and engineering excellence.',
    items: [
      {
        text: 'Vertex Infras delivered our bridge project ahead of schedule with exceptional structural quality. Their attention to detail and proactive communication gave us complete confidence throughout.',
        name: 'Rajesh Patel', role: 'Director, Metro Transport Authority', stars: 5,
      },
      {
        text: 'Working with Vertex on our township project was seamless. Their sustainable engineering approach and world-class project management make them our go-to partner for large-scale developments.',
        name: 'Anita Sharma', role: 'CEO, GreenBuild Developers', stars: 5,
      },
      {
        text: 'The highway expansion was executed flawlessly. Vertex\'s engineering team handled complex geotechnical challenges with remarkable expertise. They turned our vision into a road that transforms the region.',
        name: 'Vikram Kulkarni', role: 'Chief Engineer, NHAI Western Division', stars: 5,
      },
    ],
  },

  // ── CONTACT ───────────────────────────────────
  contact: {
    tag: 'Get In Touch',
    heading: 'Your Dream Home<br>Awaits',
    desc: 'Whether you\'re looking for a premium apartment, an independent villa, or a plot in our upcoming townships — our team is ready to guide you every step of the way.',
    services: [
      'Premium Apartments',
      'Independent Villas',
      'Plots & Layouts',
      'Township Living',
      'Commercial Spaces',
      'Other Enquiry',
    ],
  },

  // ── FOOTER ────────────────────────────────────
  footer: {
    desc: 'Engineering India\'s infrastructure future with precision, innovation, and an unwavering commitment to excellence.',
    columns: [
      { title: 'Company', links: [
        { text: 'About Us',  href: 'about.html' },
        { text: 'Projects',  href: 'projects.html' },
        { text: 'Careers',   href: '#' },
        { text: 'News',      href: '#' },
      ]},
      { title: 'Services', links: [
        { text: 'Structural Design',    href: '#' },
        { text: 'Highway Engineering',  href: '#' },
        { text: 'Water & Environment',  href: '#' },
        { text: 'Project Management',   href: '#' },
      ]},
      { title: 'Connect', links: [
        { text: 'Contact Us', href: 'contact.html' },
        { text: 'LinkedIn',   href: '#' },
        { text: 'Twitter',    href: '#' },
        { text: 'Instagram',  href: '#' },
      ]},
    ],
  },
};