// Edit this file to update site content.

const SITE = {

  // ── BRAND ─────────────────────────────────────
  name: 'Vertex Infras',
  fullName: 'Vertex Infras',
  tagline: 'Towards Finest Engineering',
  email: 'hello@vertexinfras.com',
  projectsEmail: 'projects@vertexinfras.com',
  phone: ['+91 22 4567 8900', '+91 98765 43210'],
  address: '123 Infrastructure Lane, Bandra West<br>Mumbai, Maharashtra 400050',
  social: {
    linkedin: '#',
    twitter: '#',
    instagram: '#',
  },

  // ── NAVIGATION ────────────────────────────────
  nav: [
    { text: 'Home',         href: 'index.html' },
    { text: 'About',        href: 'about.html' },
    { text: 'Projects',     href: 'projects.html' },
    { text: 'Testimonials', href: 'testimonials.html' },
    { text: 'Contact',      href: 'contact.html' },
  ],

  // ── PAGE BANNERS (inner pages) ────────────────
  banners: {
    about:        { title: 'About Us',      sub: 'Precision engineering, lasting impact' },
    projects:     { title: 'Our Projects',   sub: 'A portfolio of landmark infrastructure' },
    testimonials: { title: 'Testimonials',   sub: 'Trusted by industry leaders across India' },
    contact:      { title: 'Contact Us',     sub: 'Find your dream home, apartment, or villa — we\'re here to help' },
  },

  // ── HERO (home only) ─────────────────────────
  hero: {
    heading: 'The Home You Deserve,<br>The Life You <em>Earned</em>',
    sub: 'Every detail thoughtfully designed, every space carefully crafted — because where you live should feel as good as the life you\'ve worked hard to build.',
    ctaPrimary: { text: 'Explore Projects', href: 'projects.html' },
    ctaSecondary: { text: 'Our Story', href: 'about.html' },
  },

  // ── STATS ─────────────────────────────────────
  stats: [
    { value: 55, label: 'Projects Delivered' },
    { value: 27, label: 'Years of Excellence' },
  ],

  // Full-bleed sections on the home page. Uncomment `image` when you have real photos.
  featured: [
    {
      title: 'Vertex Vista',
      subtitle: '4 BHK luxury villas in Varthur',
      tag: 'Ready to Move In',
      badge: 'Ready to Move In',
      desc: 'Spacious 4 BHK independent villas in a premium gated community in Varthur, Bengaluru — ready for immediate possession.',
      stat1: { value: '21', label: 'Villas' },
      stat2: { value: '4 BHK', label: 'Configuration' },
      stat3: { value: 'Varthur', label: 'Location' },
      bg: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 40%, #1e1e1e 100%)',
      // image: 'images/vista-hero.jpg',
      cta: { text: 'View Project', href: 'projects.html' },
    },
    {
      title: 'Vertex Wellington',
      subtitle: 'Premium apartments in Gunjur',
      tag: 'Booking Open',
      badge: 'Selling Fast',
      desc: 'Well-planned 2 & 3 BHK apartments in the rapidly growing Gunjur corridor, with excellent connectivity to Sarjapur Road.',
      stat1: { value: '2 & 3', label: 'BHK' },
      stat2: { value: 'Gunjur', label: 'Location' },
      stat3: { value: '2025', label: 'Possession' },
      bg: 'linear-gradient(135deg, #1e1e1e 0%, #2a2a20 40%, #1e1e1e 100%)',
      // image: 'images/wellington-hero.jpg',
      cta: { text: 'View Project', href: 'projects.html' },
    },
    {
      title: 'Vertex Vihanta',
      subtitle: 'Coming soon to Bengaluru',
      tag: 'Pre-Launch',
      badge: 'Pre-Launch',
      desc: 'Our upcoming landmark residential project — register your interest now to get early access to pricing and floor plans.',
      stat1: { value: 'TBA', label: 'Configuration' },
      stat2: { value: 'Bengaluru', label: 'Location' },
      stat3: { value: '2026', label: 'Possession' },
      bg: 'linear-gradient(135deg, #1a1a1a 0%, #2a2528 40%, #1e1e1e 100%)',
      // image: 'images/vihanta-hero.jpg',
      cta: { text: 'Register Interest', href: 'contact.html' },
    },
  ],

  // ── ABOUT ─────────────────────────────────────
  about: {
    tag: 'Who We Are',
    heading: 'Precision Engineering,<br>Lasting Impact',
    paragraphs: [
      'Vertex Infras is a premier civil engineering consultancy committed to shaping India\'s infrastructure landscape. We bring together deep technical expertise, innovative design thinking, and an unwavering commitment to quality.',
      'From concept to completion, our multidisciplinary team delivers solutions across structural, geotechnical, transportation, and environmental engineering — projects that communities depend on for generations.',
    ],
    badgeNum: '27+',
    badgeLabel: 'Years',
    values: [
      { icon: 'check',  title: 'Quality Assurance', desc: 'ISO-certified processes at every stage' },
      { icon: 'layers', title: 'BIM Integrated',    desc: 'Advanced 3D modeling & planning' },
      { icon: 'team',   title: 'Expert Team',       desc: '50+ licensed professional engineers' },
      { icon: 'shield', title: 'Safety First',      desc: 'Zero-incident commitment on every site' },
    ],
    // Add photo paths when ready
    team: [
      {
        name: 'Pradeep Reddy',
        role: 'Founder & Managing Director',
        // photo: 'images/team/pradeep.jpg',
        bio: 'Over 27 years of experience in real estate development and civil engineering across South India.',
      },
      {
        name: 'Srinivas Reddy',
        role: 'Director, Engineering & Projects',
        // photo: 'images/team/srinivas.jpg',
        bio: 'Structural engineering expert leading large-scale residential and infrastructure projects.',
      },
      {
        name: 'Venkatesh Reddy',
        role: 'Director, Sales & Business Development',
        // photo: 'images/team/venkatesh.jpg',
        bio: 'Driving growth, customer relationships, and new project launches since 2005.',
      },
    ],
    pastProjects: [
      {
        title: 'Vertex Venezia', location: 'East Bengaluru',
        type: '2 BHK Apartments', status: 'Sold Out', year: 2020,
        // image: 'images/past/venezia.jpg',
      },
      {
        title: 'Vertex Fairmount', location: 'South Bengaluru',
        type: '2 & 3 BHK Apartments', status: 'Sold Out', year: 2019,
        // image: 'images/past/fairmount.jpg',
      },
      {
        title: 'Vertex Wellington', location: 'Gunjur, Bengaluru',
        type: '2 & 3 BHK Apartments', status: 'Sold Out', year: 2022,
        // image: 'images/past/wellington.jpg',
      },
    ],
  },

  // `bg`: card gradient class (proj-1 … proj-6). `image`: optional real photo path.
  projects: {
    tag: 'Portfolio',
    heading: 'Featured Projects',
    desc: 'A selection of landmark projects that reflect our engineering precision and commitment to excellence.',
    items: [
      {
        id: 'vertex-skyline',
        tag: 'Apartments', category: 'apartments', title: 'Vertex Skyline', bg: 'proj-1',
        desc: 'Premium 2 & 3 BHK residences with panoramic city views, rooftop amenities, and smart home features.',
        location: 'Bengaluru', year: 2024, stat: '₹240 Cr',
        status: 'Now Selling',
        fullDesc: 'Vertex Skyline redefines urban living with meticulously designed 2 & 3 BHK residences that offer sweeping views of the Mumbai skyline. Every detail — from the double-height lobbies to the Italian marble finishes — has been crafted to deliver a life of ease, comfort, and quiet luxury. Located minutes from BKC and the Western Express Highway, Vertex Skyline is where convenience meets elegance.',
        specs: { units: '248 Units', sizes: '1,050 – 1,820 sq ft', floors: 'G + 32 Floors', possession: 'Dec 2025' },
        highlights: ['Panoramic city & sea views', 'Smart home automation', 'Rooftop infinity pool & lounge', '3-tier security system', 'EV charging in every parking bay', 'IGBC Green certified building'],
        amenities: ['Swimming Pool', 'Gymnasium', 'Clubhouse', 'Children\'s Play Area', 'Landscaped Gardens', 'Jogging Track', 'Party Hall', 'Concierge Service'],
        floorPlans: [
          { label: '2 BHK', size: '1,050 – 1,240 sq ft' },
          { label: '3 BHK', size: '1,480 – 1,820 sq ft' },
        ],
        brochure: '#',
      },
      {
        id: 'vertex-green-residences',
        tag: 'Apartments', category: 'apartments', title: 'Vertex Green Residences', bg: 'proj-2',
        desc: 'Eco-certified apartments with solar power, rainwater harvesting, and lush landscaped courtyards.',
        location: 'Bengaluru', year: 2023, stat: '312 Units',
        status: 'Ready to Move In',
        fullDesc: 'Vertex Green Residences is a landmark in sustainable living. Built to IGBC Platinum standards, this community harnesses solar energy, collects and recycles rainwater, and is surrounded by over 2 acres of manicured green spaces. These 1, 2, and 3 BHK homes are designed for families who want modern comfort without compromising on the environment.',
        specs: { units: '312 Units', sizes: '680 – 1,540 sq ft', floors: 'G + 18 Floors (4 Towers)', possession: 'Ready to Move' },
        highlights: ['IGBC Platinum certified', '2 acres of landscaped greens', 'Solar-powered common areas', 'Rainwater harvesting & recycling', 'Zero-waste community', 'Air-purifying vertical gardens'],
        amenities: ['Olympic-size Pool', 'Yoga & Meditation Deck', 'Organic Garden', 'Gymnasium', 'Cycling Track', 'Senior Citizen Corner', 'Amphitheatre', 'Co-working Space'],
        floorPlans: [
          { label: '1 BHK', size: '680 – 780 sq ft' },
          { label: '2 BHK', size: '980 – 1,180 sq ft' },
          { label: '3 BHK', size: '1,320 – 1,540 sq ft' },
        ],
        brochure: '#',
      },
      {
        id: 'vertex-eden-villas',
        tag: 'Villas', category: 'villas', title: 'Vertex Eden Villas', bg: 'proj-3',
        desc: 'Spacious 4 & 5 BHK private villas with personal gardens, home theatres, and resort-style pools.',
        location: 'Bengaluru', year: 2024, stat: '48 Villas',
        status: 'Now Selling',
        fullDesc: 'Vertex Eden Villas is an exclusive gated community of 48 luxury villas set across a sprawling 14-acre estate in North Bangalore. Each villa is an independent home with a private pool, landscaped garden, and fully equipped home theatre. Designed by award-winning architects, every villa balances grandeur with warmth — making it a home you\'ll never want to leave.',
        specs: { units: '48 Villas', sizes: '4,200 – 6,800 sq ft', floors: 'G + 1 Independent Villas', possession: 'Mar 2026' },
        highlights: ['Private pool with each villa', 'Dedicated home theatre room', 'Private landscaped garden', 'Double-car garage', 'Smart home & security system', 'Gated community with 24/7 security'],
        amenities: ['Clubhouse & Spa', 'Tennis Court', 'Basketball Court', 'Party Lawn', 'Children\'s Play Zone', 'Jogging Trail', 'Concierge & Maintenance', 'Guest Suites'],
        floorPlans: [
          { label: '4 BHK Villa', size: '4,200 – 4,800 sq ft' },
          { label: '5 BHK Villa', size: '5,400 – 6,800 sq ft' },
        ],
        brochure: '#',
      },
      {
        id: 'vertex-heritage',
        tag: 'Villas', category: 'villas', title: 'Vertex Heritage', bg: 'proj-4',
        desc: 'Architect-designed luxury villas blending traditional aesthetics with contemporary living.',
        location: 'Bengaluru', year: 2023, stat: '32 Villas',
        status: 'Ready to Move In',
        fullDesc: 'Vertex Heritage is a collection of 32 bespoke villas that honour the rich architectural traditions of South India while delivering every modern comfort. Chettinad-inspired façades, courtyard-style layouts, and hand-crafted interiors sit alongside smart home technology, energy-efficient systems, and premium finishes — creating homes with a soul.',
        specs: { units: '32 Villas', sizes: '3,600 – 5,200 sq ft', floors: 'G + 1 Independent Villas', possession: 'Ready to Move' },
        highlights: ['Chettinad-inspired architecture', 'Central courtyard with water feature', 'Hand-crafted woodwork & stonework', 'Solar power & rainwater harvesting', 'Private terrace garden', 'Vastu-compliant layouts'],
        amenities: ['Heritage Clubhouse', 'Swimming Pool', 'Gymnasium', 'Temple & Meditation Space', 'Organic Kitchen Garden', 'Children\'s Play Area', '24/7 Security', 'Housekeeping Services'],
        floorPlans: [
          { label: '3 BHK Villa', size: '3,600 – 3,900 sq ft' },
          { label: '4 BHK Villa', size: '4,200 – 5,200 sq ft' },
        ],
        brochure: '#',
      },
      {
        id: 'metro-river-bridge',
        tag: 'Infrastructure', category: 'other', title: 'Metro River Bridge', bg: 'proj-5',
        desc: 'A 1.2 km cable-stayed bridge with dual carriageway connecting two major urban districts.',
        location: 'Hyderabad', year: 2024, stat: '₹180 Cr',
        status: 'Completed',
        fullDesc: 'The Metro River Bridge is a 1.2 km cable-stayed landmark connecting two major urban districts of Hyderabad across the Musi River. Designed to carry 80,000 vehicles daily, the bridge features a dual carriageway, dedicated pedestrian walkways, and is illuminated by an award-winning lighting design. Completed ahead of schedule in 2024, it stands as a symbol of modern engineering excellence.',
        specs: { units: '1.2 km Span', sizes: 'Dual Carriageway + Pedestrian', floors: 'N/A', possession: 'Completed 2024' },
        highlights: ['1.2 km cable-stayed span', 'Capacity of 80,000 vehicles/day', 'Dedicated pedestrian & cycling path', 'Award-winning LED lighting', 'Seismic Zone III compliant', 'Completed 3 months ahead of schedule'],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
      {
        id: 'green-valley-township',
        tag: 'Township', category: 'other', title: 'Green Valley Township', bg: 'proj-6',
        desc: '200-acre integrated township with road network, utilities, and community infrastructure.',
        location: 'Hyderabad', year: 2024, stat: '200 Acres',
        status: 'Ongoing',
        fullDesc: 'Green Valley Township is a 200-acre fully integrated urban development that includes residential zones, commercial areas, schools, healthcare facilities, and parks — all connected by a modern internal road network. Designed with smart city principles at its core, the township features solar street lighting, a centralised waste management system, and digital governance infrastructure.',
        specs: { units: '200 Acres', sizes: 'Mixed-Use Development', floors: 'N/A', possession: 'Phased: 2024–2027' },
        highlights: ['200-acre mixed-use master plan', 'Smart city infrastructure', 'Solar-powered street lighting', 'Centralised waste management', 'Schools, hospitals & retail zones', 'Digital governance systems'],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
      {
        id: 'infosys-campus-bengaluru',
        tag: 'Contract', category: 'other', title: 'Infosys Campus Development', bg: 'proj-1',
        desc: 'Civil and structural works for Infosys campus infrastructure in Bengaluru.',
        location: 'Bengaluru', year: 2018, stat: 'Contract',
        status: 'Completed',
        fullDesc: 'Vertex Infras executed civil and structural works for the Infosys campus development in Bengaluru. The scope covered site development, internal road network, drainage systems, and structural works for support buildings — delivered on time to meet Infosys\'s operational timelines.',
        specs: { units: 'N/A', sizes: 'Campus Infrastructure', floors: 'N/A', possession: 'Completed 2018' },
        highlights: ['Campus road network & paving', 'Drainage & utility infrastructure', 'Structural works for support buildings', 'Delivered on schedule'],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
      {
        id: 'gmr-group-hyderabad',
        tag: 'Contract', category: 'other', title: 'GMR Group Infrastructure Works', bg: 'proj-2',
        desc: 'Infrastructure and civil works for GMR Group projects in Hyderabad.',
        location: 'Hyderabad', year: 2020, stat: 'Contract',
        status: 'Completed',
        fullDesc: 'Vertex Infras partnered with GMR Group to execute infrastructure and civil works at their Hyderabad developments. The project included site preparation, civil structures, utility installation, and road infrastructure — delivered to GMR\'s exacting quality standards.',
        specs: { units: 'N/A', sizes: 'Infrastructure Works', floors: 'N/A', possession: 'Completed 2020' },
        highlights: ['Site preparation & earthworks', 'Civil structures & foundations', 'Utility & drainage installation', 'Road and access infrastructure'],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
      {
        id: 'kempegowda-airport-bengaluru',
        tag: 'Contract', category: 'other', title: 'Kempegowda International Airport', bg: 'proj-3',
        desc: 'Civil and infrastructure works for Kempegowda International Airport, Bengaluru.',
        location: 'Bengaluru', year: 2022, stat: 'Contract',
        status: 'Completed',
        fullDesc: 'Vertex Infras carried out civil and infrastructure works at Kempegowda International Airport, Bengaluru. The scope included structural works, pavement, drainage systems, and utility infrastructure in support of the airport\'s expansion and operational requirements.',
        specs: { units: 'N/A', sizes: 'Airport Infrastructure', floors: 'N/A', possession: 'Completed 2022' },
        highlights: ['Structural & pavement works', 'Drainage & stormwater systems', 'Utility infrastructure', 'Executed to aviation safety standards'],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
    ],
    pastProjects: [
      {
        id: 'vertex-venezia',
        title: 'Vertex Venezia', location: 'East Bengaluru',
        type: '2 BHK Apartments', category: 'apartments', status: 'Sold Out', year: 2020,
        tag: 'Apartments', bg: 'proj-1',
        fullDesc: 'Vertex Venezia was a boutique residential community of 120 well-designed 2 BHK apartments in East Bengaluru. Inspired by Italian architecture, it featured colonnaded walkways, a grand fountain courtyard, and warm, welcoming interiors. Fully sold out within 6 months of launch.',
        specs: { units: '120 Units', sizes: '980 – 1,150 sq ft', floors: 'G + 12 Floors', possession: 'Delivered 2020' },
        highlights: ['Italian-inspired architecture', 'Grand fountain courtyard', 'Modular kitchen fittings', 'Covered car parking', '24/7 security', 'Close to Whitefield IT hub'],
        amenities: ['Swimming Pool', 'Gymnasium', 'Clubhouse', 'Children\'s Play Area', 'Landscaped Gardens'],
        floorPlans: [{ label: '2 BHK', size: '980 – 1,150 sq ft' }],
        brochure: '#',
      },
      {
        id: 'vertex-fairmount',
        title: 'Vertex Fairmount', location: 'South Bengaluru',
        type: '2 & 3 BHK Apartments', category: 'apartments', status: 'Sold Out', year: 2019,
        tag: 'Apartments', bg: 'proj-2',
        fullDesc: 'Vertex Fairmount set the standard for affordable luxury in South Bengaluru. With 2 and 3 BHK units spread across twin towers, the project offered spacious layouts, premium finishes, and a full suite of amenities at a competitive price point. Sold out well before possession.',
        specs: { units: '210 Units', sizes: '1,100 – 1,600 sq ft', floors: 'G + 20 Floors (2 Towers)', possession: 'Delivered 2019' },
        highlights: ['Twin-tower design', 'Spacious open-plan layouts', 'Premium sanitary fittings', 'Vastu-compliant', 'Near NICE Ring Road', 'Fully sold before possession'],
        amenities: ['Rooftop Pool', 'Gymnasium', 'Multipurpose Hall', 'Jogging Track', 'Children\'s Play Area'],
        floorPlans: [{ label: '2 BHK', size: '1,100 – 1,280 sq ft' }, { label: '3 BHK', size: '1,420 – 1,600 sq ft' }],
        brochure: '#',
      },
      {
        id: 'vertex-oakwood-villas',
        title: 'Vertex Oakwood Villas', location: 'Whitefield, Bengaluru',
        type: '4 BHK Villas', category: 'villas', status: 'Sold Out', year: 2021,
        tag: 'Villas', bg: 'proj-3',
        fullDesc: 'Vertex Oakwood Villas was an exclusive enclave of 36 independent villas nestled in the greenery of Whitefield. Each villa came with a private garden, semi-basement, and double-height living areas. The project received the Best Luxury Villa Project award at the Bangalore Realty Awards 2022.',
        specs: { units: '36 Villas', sizes: '3,800 – 4,600 sq ft', floors: 'G + 1 Independent Villas', possession: 'Delivered 2021' },
        highlights: ['Award-winning luxury project', 'Private garden with each villa', 'Double-height living areas', 'Semi-basement storage', 'Gated community', 'Close to ITPL & Whitefield station'],
        amenities: ['Clubhouse', 'Swimming Pool', 'Tennis Court', 'Concierge', 'Landscaped Trails'],
        floorPlans: [{ label: '4 BHK Villa', size: '3,800 – 4,600 sq ft' }],
        brochure: '#',
      },
      {
        id: 'vertex-wellington',
        title: 'Vertex Wellington', location: 'Gunjur, Bengaluru',
        type: '2 & 3 BHK Apartments', category: 'apartments', status: 'Sold Out', year: 2022,
        tag: 'Apartments', bg: 'proj-4',
        fullDesc: 'Vertex Wellington brought thoughtfully planned 2 and 3 BHK apartments to the rapidly developing Gunjur corridor. With excellent connectivity to Sarjapur Road and Outer Ring Road, and a full amenities package, Wellington became one of the fastest-selling projects in the micro-market.',
        specs: { units: '180 Units', sizes: '1,020 – 1,480 sq ft', floors: 'G + 15 Floors', possession: 'Delivered 2022' },
        highlights: ['Fast-selling project in micro-market', 'Close to Sarjapur & ORR', 'Energy-efficient design', 'Reserved green zones', 'Branded fixtures & fittings', 'High rental yield area'],
        amenities: ['Swimming Pool', 'Gymnasium', 'Clubhouse', 'Children\'s Play Area', 'Party Hall'],
        floorPlans: [{ label: '2 BHK', size: '1,020 – 1,180 sq ft' }, { label: '3 BHK', size: '1,300 – 1,480 sq ft' }],
        brochure: '#',
      },
      {
        id: 'nh48-expressway',
        title: 'NH-48 Expressway Expansion', location: 'Gujarat',
        type: 'Highway Infrastructure', category: 'other', status: 'Sold Out', year: 2023,
        tag: 'Infrastructure', bg: 'proj-5',
        fullDesc: 'The NH-48 Expressway Expansion was a 85 km highway upgrade project across Gujarat, converting a 4-lane national highway into a modern 6-lane expressway with grade separators, toll plazas, and service roads. Completed on time and within budget, the project significantly reduced travel time between two major cities.',
        specs: { units: '85 km', sizes: '6-Lane Expressway', floors: 'N/A', possession: 'Delivered 2023' },
        highlights: ['85 km 6-lane expressway', '12 flyovers & underpasses', 'Modern toll infrastructure', 'LED road lighting throughout', 'Completed on time & budget', 'Serves 1.2 lakh vehicles/day'],
        amenities: [],
        floorPlans: [],
        brochure: '#',
      },
    ],
  },

  // ── TESTIMONIALS ──────────────────────────────
  testimonials: {
    tag: 'Client Voices',
    heading: 'Trusted by Industry Leaders',
    desc: 'Our reputation is built on consistently exceeding expectations through transparent communication and engineering excellence.',
    items: [
      {
        text: 'Vertex Infras delivered our bridge project ahead of schedule with exceptional structural quality. Their attention to detail and proactive communication gave us complete confidence throughout.',
        name: 'Rajesh Patel', role: 'Director, Metro Transport Authority', stars: 5,
      },
      {
        text: 'Working with Vertex on our township project was seamless. Their sustainable engineering approach and world-class project management make them our go-to partner for large-scale developments.',
        name: 'Anita Sharma', role: 'CEO, GreenBuild Developers', stars: 5,
      },
      {
        text: 'The highway expansion was executed flawlessly. Vertex\'s engineering team handled complex geotechnical challenges with remarkable expertise. They turned our vision into a road that transforms the region.',
        name: 'Vikram Kulkarni', role: 'Chief Engineer, NHAI Western Division', stars: 5,
      },
    ],
  },

  // ── CONTACT ───────────────────────────────────
  contact: {
    tag: 'Get In Touch',
    heading: 'Your Dream Home<br>Awaits',
    desc: 'Whether you\'re looking for a premium apartment, an independent villa, or a plot in our upcoming townships — our team is ready to guide you every step of the way.',
    services: [
      'Premium Apartments',
      'Independent Villas',
      'Plots & Layouts',
      'Township Living',
      'Commercial Spaces',
      'Other Enquiry',
    ],
  },

  // ── FOOTER ────────────────────────────────────
  footer: {
    desc: 'Engineering India\'s infrastructure future with precision, innovation, and an unwavering commitment to excellence.',
    columns: [
      { title: 'Company', links: [
        { text: 'About Us',  href: 'about.html' },
        { text: 'Projects',  href: 'projects.html' },
        { text: 'Careers',   href: '#' },
        { text: 'News',      href: '#' },
      ]},
      { title: 'Services', links: [
        { text: 'Structural Design',    href: '#' },
        { text: 'Highway Engineering',  href: '#' },
        { text: 'Water & Environment',  href: '#' },
        { text: 'Project Management',   href: '#' },
      ]},
      { title: 'Connect', links: [
        { text: 'Contact Us', href: 'contact.html' },
        { text: 'LinkedIn',   href: '#' },
        { text: 'Twitter',    href: '#' },
        { text: 'Instagram',  href: '#' },
      ]},
    ],
  },
};